apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.helm.repoURL }}
    targetRevision: {{ .Values.helm.targetRevision }}
    chart: {{ .Values.helm.chartName }}
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        appConf:
{{ toYaml .Values.appConf | indent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
