helm:
  repoURL: "http://10.155.255.182/repos"
  targetRevision: 0.1.3
  chartName: op-gateway

appConf:
  app.security:
    white-list:
      - /iam-service/swagger-ui/**
      - /iam-service/openapi/**
    allowlist:
      - /favicon.ico
      - /actuator/**
      - /*/openapi/**
  app.proxy:
    services:
      - type: NVO
        name: traefik
        uri: http://traefik:80
        context-path: /nvo
        predicate-path: /nvo/**