---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: iam-gateway-controller
    app.kubernetes.io/version: 1.0.2
  name: iamgatewaycontroller-crd-validating-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: iam-gateway-controller
    namespace: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: iam-gateway-controller
    app.kubernetes.io/version: 1.0.2
  name: iamgatewaycontroller-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: iamgatewaycontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: iam-gateway-controller
    namespace: operator
