---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: iam-gateway-controller
    app.kubernetes.io/version: 1.0.2
  name: iamgatewaycontroller-cluster-role
rules:
  - apiGroups:
      - devops.extremecloud.com
    resources:
      - iamgatewayconfigurations
      - iamgatewayconfigurations/status
      - iamgatewayconfigurations/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: iam-gateway-controller
    app.kubernetes.io/version: 1.0.2
  name: josdk-crd-validating-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
