---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.21.4
    app.quarkus.io/commit-id: ba424ea340d567d70ce6ef1fba9c4718d1bc64fc
    app.quarkus.io/vcs-uri: https://github.com/extremenetworks/xcloud-operator.git
    app.quarkus.io/build-timestamp: 2025-05-05 - 11:00:01 +0000
  labels:
    app.kubernetes.io/name: iam-gateway-controller
    app.kubernetes.io/version: 1.0.2
    app.kubernetes.io/managed-by: quarkus
  name: iam-gateway-controller
  namespace: operator
