apiVersion: batch/v1
kind: Job
metadata:
  name: delete-{{ .Release.Name }}-pvc-hook
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: pvc-admin
      containers:
      - name: delete-pvc
        image: public.ecr.aws/extremecloud/kubectl
        command:
        - /bin/sh
        - -c
        - |
          kubectl delete pvc --all --wait=true -n {{ .Values.global.namespace }}
      restartPolicy: Never
