apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  generators:
    - list:
        elements:
          {{- toYaml .Values.applications | nindent 10 }}
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      project: default
      source:
        repoURL: {{ .Values.helm.repoURL }}
        targetRevision: "{{ .Values.helm.targetRevision }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd